sudo: false
matrix:
  include:
    # Linux :: Python :: 2.7
    - os: linux
      language: python
      python: "2.7"
      install:
        - pip install -U pip setuptools tox
      script:
        - python --version
        - tox -e py
    # Linux :: Python :: 3.6
    - os: linux
      language: python
      python: "3.6"
      install:
        - pip install -U pip setuptools tox
      script:
        - python --version
        - tox -e py
    # OSX :: Python :: 2.7
    - os: osx
      language: generic
      env: PYTHON=2.7
      before_install:
        - brew install python@2 || true
      install:
        - /usr/local/bin/pip install -U pip setuptools tox
      script:
        - /usr/local/bin/python2 --version
        - /usr/local/bin/python2 -m tox -e py
    # OSX :: Python :: 3.x
    - os: osx
      language: generic
      env: PYTHON=3.x
      before_install:
        - brew upgrade python
      install:
        - /usr/local/bin/pip3 install -U pip setuptools tox
      script:
        - /usr/local/bin/python3 --version
        - /usr/local/bin/python3 -m tox -e py
    # Linux :: Python :: 3.6 :: flake8
    - os: linux
      language: python
      python: "3.6"
      install:
        - pip install -U pip setuptools tox
        - tox -e flake8

